import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layouts/Nav";
import SvgDefs from "@/components/SvgDefs/SvgDefs";
import Copyrights from "@/components/layouts/Copyrights";
import Footer from "@/components/layouts/Footer";
import { myFontConfig } from "@/fonts/Obviously/obviously";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${myFontConfig.variable} antialiased`}>
        <SvgDefs />
        <Navbar />
        <main>{children}</main>
        <Footer />
        <Copyrights />
      </body>
    </html>
  );
}
